//! Generates Rust struct definitions from every `structs/*.json` IR
//! document into a single `$OUT_DIR/ffstructs.rs`.
//!
//! A struct whose layout is identical in every JSON file that declares
//! it is emitted once at the crate root. As soon as a single version
//! disagrees, the struct is emitted separately into every version
//! module that declares it (`v<stem>`, since Rust identifiers can't
//! start with a digit). A struct only counts as identical if its nested
//! struct references are identical too, so a layout change ripples out
//! to everything that embeds it.
//!
//! Layouts are compared by alignment rather than by declared `pack`: a
//! `pack` wider than the struct's widest field is a no-op, so versions
//! that only disagree on a redundant `pack` still share one definition.
//!
//! Per-struct output mirrors the hand-maintained style previously used
//! by RustyFusion:
//!
//! ```ignore
//! #[repr(packed(N))]
//! #[repr(C)]
//! #[derive(Debug, Copy, Clone)]
//! pub struct sFoo { ... }
//! impl FFPacket for sFoo {}
//! ```
//!
//! Structs are emitted in topological order so nested-struct references
//! always come after their dependencies. Empty packet bodies are
//! emitted as zero-sized unit structs.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

const STRUCTS_DIR: &str = "structs";

struct VersionDoc {
    file_name: String,
    module: String,
    default_pack: u32,
    structs: Vec<Value>,
}

fn main() {
    println!("cargo:rerun-if-changed={STRUCTS_DIR}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let structs_dir = manifest_dir.join(STRUCTS_DIR);

    let mut version_files: Vec<PathBuf> = fs::read_dir(&structs_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", structs_dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
        .collect();
    version_files.sort();

    let mut docs: Vec<VersionDoc> = Vec::new();
    for path in &version_files {
        println!("cargo:rerun-if-changed={}", path.display());

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("bad file name: {}", path.display()));
        docs.push(load_version(path, format!("v{stem}")));
    }

    let shared = shared_structs(&docs);

    let mut out = String::new();
    out.push_str("// @generated by build.rs -- DO NOT EDIT\n\n");

    render_shared_structs(&docs, &shared, &mut out);
    for doc in &docs {
        render_version_module(doc, &shared, &mut out);
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("ffstructs.rs");
    fs::write(&out_path, out).expect("failed to write generated ffstructs.rs");
}

fn load_version(path: &Path, module: String) -> VersionDoc {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let doc: Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

    let default_pack = doc
        .get("defaults")
        .and_then(|v| v.get("pack"))
        .and_then(|v| v.as_u64())
        .unwrap_or(4) as u32;

    let structs = doc
        .get("structs")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("{}: missing top-level `structs` array", path.display()))
        .clone();

    VersionDoc {
        file_name: path.file_name().unwrap().to_string_lossy().into_owned(),
        module,
        default_pack,
        structs,
    }
}

fn effective_pack(s: &Value, default_pack: u32) -> u32 {
    s.get("pack")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(default_pack)
}

fn struct_refs(s: &Value) -> impl Iterator<Item = &str> {
    s["fields"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|f| f.get("type").and_then(|t| t.as_str()) == Some("struct"))
        .map(|f| f["ref"].as_str().unwrap())
}

fn prim_align(ty: &str) -> Option<u32> {
    Some(match ty {
        "i8" | "u8" => 1,
        "i16" | "u16" => 2,
        "i32" | "u32" | "f32" => 4,
        "i64" | "u64" | "f64" => 8,
        _ => return None,
    })
}

/// Alignment of every struct: its declared `pack` clamped to the widest
/// alignment any of its fields actually needs. A `pack` wider than that
/// is a no-op, so two structs with the same fields and the same clamped
/// value are byte-identical even if their declared packing differs.
fn struct_aligns(structs: &[Value], default_pack: u32) -> HashMap<String, u32> {
    let mut aligns: HashMap<String, u32> = HashMap::new();
    // Topological order guarantees nested structs are resolved first.
    for s in topo_sort(structs) {
        let widest = s["fields"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| match f["type"].as_str().unwrap() {
                "wstr" => 2,
                "struct" => *aligns.get(f["ref"].as_str().unwrap()).unwrap_or(&1),
                other => {
                    prim_align(other).unwrap_or_else(|| panic!("unsupported IR type {other:?}"))
                }
            })
            .max()
            .unwrap_or(1);
        let align = effective_pack(&s, default_pack).min(widest);
        aligns.insert(s["name"].as_str().unwrap().to_string(), align);
    }
    aligns
}

/// Canonical description of a struct's memory layout. Equal fingerprints
/// mean one definition can stand in for the other.
fn fingerprint(s: &Value, align: u32) -> String {
    let mut fp = format!(
        "align={align};size={:?};",
        s.get("size").and_then(|v| v.as_u64())
    );
    for f in s["fields"].as_array().unwrap() {
        fp.push_str(&format!(
            "{:?}:{:?}:{:?}:{:?}:{:?}|",
            f.get("name").and_then(|v| v.as_str()),
            f.get("type").and_then(|v| v.as_str()),
            f.get("ref").and_then(|v| v.as_str()),
            f.get("array").and_then(|v| v.as_u64()),
            f.get("length").and_then(|v| v.as_u64()),
        ));
    }
    fp
}

/// Names that every version declares with an identical layout, and
/// whose nested struct references are themselves all shared. These are
/// emitted once at the crate root; everything else is per-version.
fn shared_structs(docs: &[VersionDoc]) -> BTreeSet<String> {
    let fps: Vec<HashMap<&str, String>> = docs
        .iter()
        .map(|d| {
            let aligns = struct_aligns(&d.structs, d.default_pack);
            d.structs
                .iter()
                .map(|s| {
                    let name = s["name"].as_str().unwrap();
                    (name, fingerprint(s, aligns[name]))
                })
                .collect()
        })
        .collect();

    let Some((first, rest)) = fps.split_first() else {
        return BTreeSet::new();
    };

    // A name missing from any version counts as a difference, so every
    // other version's map has to carry the same fingerprint.
    let mut shared: BTreeSet<String> = first
        .iter()
        .filter(|(name, fp)| rest.iter().all(|other| other.get(**name) == Some(*fp)))
        .map(|(name, _)| (*name).to_string())
        .collect();

    // A struct embedding a per-version struct can't live at the root, so
    // keep dropping until the set is closed under its references.
    loop {
        let drop: Vec<String> = docs[0]
            .structs
            .iter()
            .filter(|s| shared.contains(s["name"].as_str().unwrap()))
            .filter(|s| struct_refs(s).any(|r| !shared.contains(r)))
            .map(|s| s["name"].as_str().unwrap().to_string())
            .collect();
        if drop.is_empty() {
            break;
        }
        for name in drop {
            shared.remove(&name);
        }
    }

    shared
}

/// Emits the version-independent structs at the crate root, taking the
/// definitions from the first version (they are identical everywhere).
fn render_shared_structs(docs: &[VersionDoc], shared: &BTreeSet<String>, out: &mut String) {
    let Some(doc) = docs.first() else {
        return;
    };

    let ordered: Vec<Value> = topo_sort(&doc.structs)
        .into_iter()
        .filter(|s| shared.contains(s["name"].as_str().unwrap()))
        .collect();

    for s in &ordered {
        render_struct(s, doc.default_pack, "", out);
        out.push('\n');
    }
    render_size_assertions(&ordered, "", out);
    out.push('\n');
}

fn render_version_module(doc: &VersionDoc, shared: &BTreeSet<String>, out: &mut String) {
    let ordered = topo_sort(&doc.structs);

    let names: HashSet<&str> = doc
        .structs
        .iter()
        .map(|s| s["name"].as_str().unwrap())
        .collect();
    let mut unresolved: BTreeSet<String> = BTreeSet::new();
    for s in &doc.structs {
        for r in struct_refs(s) {
            if !names.contains(r) {
                unresolved.insert(r.to_string());
            }
        }
    }
    if !unresolved.is_empty() {
        println!(
            "cargo:warning=ffproto/{}: {} unresolved struct ref(s): {}",
            doc.file_name,
            unresolved.len(),
            unresolved.iter().cloned().collect::<Vec<_>>().join(", "),
        );
    }

    let local: Vec<Value> = ordered
        .into_iter()
        .filter(|s| !shared.contains(s["name"].as_str().unwrap()))
        .collect();

    out.push_str(&format!("pub mod {} {{\n", doc.module));
    out.push_str("    #[allow(unused_imports)]\n");
    out.push_str("    use super::FFPacket;\n");

    // Root structs are not re-exported here; they are only imported when
    // a version-specific struct embeds one.
    let imports: BTreeSet<&str> = local
        .iter()
        .flat_map(struct_refs)
        .filter(|r| shared.contains(*r))
        .collect();
    if !imports.is_empty() {
        out.push_str("    use super::{\n");
        for name in &imports {
            out.push_str(&format!("        {name},\n"));
        }
        out.push_str("    };\n");
    }
    out.push('\n');

    for s in &local {
        render_struct(s, doc.default_pack, "    ", out);
        out.push('\n');
    }
    render_size_assertions(&local, "    ", out);

    out.push_str("}\n\n");
}

/// Compile-time size checks catch IR drift.
fn render_size_assertions(structs: &[Value], indent: &str, out: &mut String) {
    for s in structs {
        let name = s["name"].as_str().unwrap();
        let Some(size) = s.get("size").and_then(|v| v.as_u64()) else {
            continue;
        };
        out.push_str(&format!(
            "{indent}const _: () = assert!(::core::mem::size_of::<{name}>() == {size});\n"
        ));
    }
}

fn prim_to_rust(ty: &str) -> Option<&'static str> {
    Some(match ty {
        "i8" => "i8",
        "u8" => "u8",
        "i16" => "i16",
        "u16" => "u16",
        "i32" => "i32",
        "u32" => "u32",
        "i64" => "i64",
        "u64" => "u64",
        "f32" => "f32",
        "f64" => "f64",
        _ => return None,
    })
}

fn render_field(f: &Value, indent: &str, out: &mut String) {
    let name = f["name"].as_str().unwrap();
    let ty = f["type"].as_str().unwrap();
    let array = f.get("array").and_then(|v| v.as_u64());
    let length = f.get("length").and_then(|v| v.as_u64());
    let r#ref = f.get("ref").and_then(|v| v.as_str());

    let base = match ty {
        "wstr" => {
            let len = length.expect("wstr field missing `length`");
            out.push_str(&format!("{indent}    pub {name}: [u16; {len}],\n"));
            return;
        }
        "struct" => r#ref.expect("struct field missing `ref`").to_string(),
        other => prim_to_rust(other)
            .unwrap_or_else(|| panic!("unsupported IR type {other:?} on field {name:?}"))
            .to_string(),
    };

    match array {
        Some(n) => out.push_str(&format!("{indent}    pub {name}: [{base}; {n}],\n")),
        None => out.push_str(&format!("{indent}    pub {name}: {base},\n")),
    }
}

fn render_struct(s: &Value, default_pack: u32, indent: &str, out: &mut String) {
    let name = s["name"].as_str().unwrap();
    let fields = s["fields"].as_array().unwrap();
    let pack = effective_pack(s, default_pack);

    out.push_str(&format!("{indent}#[repr(packed({pack}))]\n"));
    out.push_str(&format!("{indent}#[repr(C)]\n"));
    out.push_str(&format!("{indent}#[derive(Debug, Copy, Clone)]\n"));
    out.push_str(&format!("{indent}pub struct {name} {{\n"));
    for f in fields {
        render_field(f, indent, out);
    }
    out.push_str(&format!("{indent}}}\n"));
    out.push_str(&format!("{indent}impl FFPacket for {name} {{}}\n"));
    out.push_str(&format!(
        "{indent}impl Default for {name} {{\n{indent}    fn default() -> Self {{ unsafe {{ ::core::mem::zeroed() }} }}\n{indent}}}\n"
    ));
}

fn topo_sort(structs: &[Value]) -> Vec<Value> {
    let by_name: HashMap<&str, &Value> = structs
        .iter()
        .map(|s| (s["name"].as_str().unwrap(), s))
        .collect();
    let order_index: HashMap<&str, usize> = structs
        .iter()
        .enumerate()
        .map(|(i, s)| (s["name"].as_str().unwrap(), i))
        .collect();

    fn deps<'a>(
        name: &str,
        by_name: &HashMap<&'a str, &'a Value>,
        order_index: &HashMap<&str, usize>,
    ) -> Vec<&'a str> {
        let s = by_name[name];
        let mut out = Vec::new();
        for f in s["fields"].as_array().unwrap() {
            if f.get("type").and_then(|t| t.as_str()) == Some("struct") {
                let r = f["ref"].as_str().unwrap();
                if let Some((&k, _)) = by_name.get_key_value(r) {
                    out.push(k);
                }
            }
        }
        out.sort_by_key(|n| order_index[n]);
        out
    }

    let mut emitted: HashSet<&str> = HashSet::new();
    let mut result: Vec<Value> = Vec::new();

    enum Frame<'a> {
        Enter(&'a str),
        Exit(&'a str),
    }

    let mut on_stack: HashSet<&str> = HashSet::new();
    for s in structs {
        let root = s["name"].as_str().unwrap();
        if emitted.contains(root) {
            continue;
        }
        let mut stack: Vec<Frame> = vec![Frame::Enter(root)];
        while let Some(frame) = stack.pop() {
            match frame {
                Frame::Enter(name) => {
                    if emitted.contains(name) || on_stack.contains(name) {
                        continue;
                    }
                    on_stack.insert(name);
                    stack.push(Frame::Exit(name));
                    for d in deps(name, &by_name, &order_index).into_iter().rev() {
                        stack.push(Frame::Enter(d));
                    }
                }
                Frame::Exit(name) => {
                    on_stack.remove(name);
                    if emitted.insert(name) {
                        result.push(by_name[name].clone());
                    }
                }
            }
        }
    }

    result
}
