//! Generates Rust struct definitions from every `structs/*.json` IR
//! document into a single `$OUT_DIR/ffstructs.rs`.
//!
//! Each JSON file becomes a module named `v<stem>` (Rust identifiers
//! can't start with a digit). The `0104` module is additionally
//! re-exported at the crate root so callers can use the legacy struct
//! names directly.
//!
//! Per-struct output mirrors the hand-maintained style previously used
//! by RustyFusion:
//!
//! ```ignore
//! #[repr(packed(N))]
//! #[repr(C)]
//! #[derive(Debug, Copy, Clone)]
//! pub struct sFoo { ... }
//! impl FFPacket for sFoo {}
//! ```
//!
//! Structs are emitted in topological order so nested-struct references
//! always come after their dependencies. Empty packet bodies are
//! emitted as zero-sized unit structs.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

const STRUCTS_DIR: &str = "structs";
const ROOT_REEXPORT_VERSION: &str = "0104";

fn main() {
    println!("cargo:rerun-if-changed={STRUCTS_DIR}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let structs_dir = manifest_dir.join(STRUCTS_DIR);

    let mut version_files: Vec<PathBuf> = fs::read_dir(&structs_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", structs_dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
        .collect();
    version_files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs -- DO NOT EDIT\n\n");

    let mut found_root_reexport = false;
    for path in &version_files {
        println!("cargo:rerun-if-changed={}", path.display());

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("bad file name: {}", path.display()));
        let module = format!("v{stem}");

        render_version_module(path, &module, &mut out);

        if stem == ROOT_REEXPORT_VERSION {
            found_root_reexport = true;
        }
    }

    if found_root_reexport {
        out.push_str(&format!(
            "\npub use v{ROOT_REEXPORT_VERSION}::*;\n"
        ));
    } else {
        println!(
            "cargo:warning=ffproto: no structs/{ROOT_REEXPORT_VERSION}.json found; \
             skipping root re-export"
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("ffstructs.rs");
    fs::write(&out_path, out).expect("failed to write generated ffstructs.rs");
}

fn render_version_module(path: &Path, module: &str, out: &mut String) {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let doc: Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

    let default_pack = doc
        .get("defaults")
        .and_then(|v| v.get("pack"))
        .and_then(|v| v.as_u64())
        .unwrap_or(4) as u32;

    let structs = doc
        .get("structs")
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("{}: missing top-level `structs` array", path.display()))
        .clone();

    let ordered = topo_sort(&structs);

    let names: HashSet<&str> = structs
        .iter()
        .map(|s| s["name"].as_str().unwrap())
        .collect();
    let mut unresolved: BTreeSet<String> = BTreeSet::new();
    for s in &structs {
        for f in s["fields"].as_array().unwrap() {
            if f.get("type").and_then(|t| t.as_str()) == Some("struct") {
                let r = f["ref"].as_str().unwrap();
                if !names.contains(r) {
                    unresolved.insert(r.to_string());
                }
            }
        }
    }
    if !unresolved.is_empty() {
        println!(
            "cargo:warning=ffproto/{}: {} unresolved struct ref(s): {}",
            path.file_name().unwrap().to_string_lossy(),
            unresolved.len(),
            unresolved.iter().cloned().collect::<Vec<_>>().join(", "),
        );
    }

    out.push_str(&format!("pub mod {module} {{\n"));
    out.push_str("    use super::FFPacket;\n\n");
    for s in &ordered {
        render_struct(s, default_pack, out);
        out.push('\n');
    }

    // Per-struct compile-time size assertions catch IR drift.
    for s in &ordered {
        let name = s["name"].as_str().unwrap();
        let size = match s.get("size").and_then(|v| v.as_u64()) {
            Some(n) => n as usize,
            None => continue,
        };
        out.push_str(&format!(
            "    const _: () = assert!(::core::mem::size_of::<{name}>() == {size});\n"
        ));
    }

    out.push_str("}\n\n");
}

fn prim_to_rust(ty: &str) -> Option<&'static str> {
    Some(match ty {
        "i8" => "i8",
        "u8" => "u8",
        "i16" => "i16",
        "u16" => "u16",
        "i32" => "i32",
        "u32" => "u32",
        "i64" => "i64",
        "u64" => "u64",
        "f32" => "f32",
        "f64" => "f64",
        _ => return None,
    })
}

fn render_field(f: &Value, out: &mut String) {
    let name = f["name"].as_str().unwrap();
    let ty = f["type"].as_str().unwrap();
    let array = f.get("array").and_then(|v| v.as_u64());
    let length = f.get("length").and_then(|v| v.as_u64());
    let r#ref = f.get("ref").and_then(|v| v.as_str());

    let base = match ty {
        "wstr" => {
            let len = length.expect("wstr field missing `length`");
            out.push_str(&format!("        pub {name}: [u16; {len}],\n"));
            return;
        }
        "struct" => r#ref.expect("struct field missing `ref`").to_string(),
        other => prim_to_rust(other)
            .unwrap_or_else(|| panic!("unsupported IR type {other:?} on field {name:?}"))
            .to_string(),
    };

    match array {
        Some(n) => out.push_str(&format!("        pub {name}: [{base}; {n}],\n")),
        None => out.push_str(&format!("        pub {name}: {base},\n")),
    }
}

fn render_struct(s: &Value, default_pack: u32, out: &mut String) {
    let name = s["name"].as_str().unwrap();
    let fields = s["fields"].as_array().unwrap();

    let pack = s
        .get("pack")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(default_pack);

    out.push_str(&format!("    #[repr(packed({pack}))]\n"));
    out.push_str("    #[repr(C)]\n");
    out.push_str("    #[derive(Debug, Copy, Clone)]\n");
    out.push_str(&format!("    pub struct {name} {{\n"));
    for f in fields {
        render_field(f, out);
    }
    out.push_str("    }\n");
    out.push_str(&format!("    impl FFPacket for {name} {{}}\n"));
    out.push_str(&format!(
        "    impl Default for {name} {{\n        fn default() -> Self {{ unsafe {{ ::core::mem::zeroed() }} }}\n    }}\n"
    ));
}

fn topo_sort(structs: &[Value]) -> Vec<Value> {
    let by_name: HashMap<&str, &Value> = structs
        .iter()
        .map(|s| (s["name"].as_str().unwrap(), s))
        .collect();
    let order_index: HashMap<&str, usize> = structs
        .iter()
        .enumerate()
        .map(|(i, s)| (s["name"].as_str().unwrap(), i))
        .collect();

    fn deps<'a>(
        name: &str,
        by_name: &HashMap<&'a str, &'a Value>,
        order_index: &HashMap<&str, usize>,
    ) -> Vec<&'a str> {
        let s = by_name[name];
        let mut out = Vec::new();
        for f in s["fields"].as_array().unwrap() {
            if f.get("type").and_then(|t| t.as_str()) == Some("struct") {
                let r = f["ref"].as_str().unwrap();
                if let Some((&k, _)) = by_name.get_key_value(r) {
                    out.push(k);
                }
            }
        }
        out.sort_by_key(|n| order_index[n]);
        out
    }

    let mut emitted: HashSet<&str> = HashSet::new();
    let mut result: Vec<Value> = Vec::new();

    enum Frame<'a> {
        Enter(&'a str),
        Exit(&'a str),
    }

    let mut on_stack: HashSet<&str> = HashSet::new();
    for s in structs {
        let root = s["name"].as_str().unwrap();
        if emitted.contains(root) {
            continue;
        }
        let mut stack: Vec<Frame> = vec![Frame::Enter(root)];
        while let Some(frame) = stack.pop() {
            match frame {
                Frame::Enter(name) => {
                    if emitted.contains(name) || on_stack.contains(name) {
                        continue;
                    }
                    on_stack.insert(name);
                    stack.push(Frame::Exit(name));
                    for d in deps(name, &by_name, &order_index).into_iter().rev() {
                        stack.push(Frame::Enter(d));
                    }
                }
                Frame::Exit(name) => {
                    on_stack.remove(name);
                    if emitted.insert(name) {
                        result.push(by_name[name].clone());
                    }
                }
            }
        }
    }

    result
}
